#!/usr/bin/env python3
"""
Initialize a business project with the minimal Zeus v3 footprint.

Usage:
    python init_project.py --project-root /path/to/business_project
    python run.py --project-root /path/to/business_project --init
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


DEFAULT_CONFIG = {
    "project": {
        "name": "ChangeMe",
        "domain": "example",
        "description": "",
        "version": "0.1.0",
        "start_date": ""
    },
    "north_star_metric": {
        "name": "",
        "target": 1.0
    },
    "subagent": {
        "dispatcher": "auto"
    }
}

EMPTY_TASK_TEMPLATE = {
    "project": {
        "name": "ChangeMe",
        "north_star": ""
    },
    "phases": [],
    "milestones": [],
    "tasks": []
}


def write_json(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def generate_start_ps1(framework_root: Path, project_root: Path) -> str:
    import os
    rel = Path(os.path.relpath(framework_root, project_root))
    rel_str = str(rel).replace("\\", "/")
    return rf'''# Auto-generated by Zeus v3 init
# This thin wrapper delegates to the framework runner.
# Do NOT edit framework code here -- edit in the framework repository instead.
$frameworkRoot = $env:ZEUS_FRAMEWORK_ROOT
if (-not $frameworkRoot) {{
    $frameworkFile = Join-Path $PSScriptRoot "..\.framework"
    if (Test-Path $frameworkFile) {{
        $frameworkRoot = Get-Content $frameworkFile -Raw -Encoding UTF8 | ForEach-Object {{ $_.Trim() }}
    }}
}}
if (-not $frameworkRoot) {{
    $frameworkRoot = Join-Path $PSScriptRoot "{rel_str}"
    $frameworkRoot = (Resolve-Path $frameworkRoot).Path
}}
$projectRoot = (Get-Item $PSScriptRoot).Parent.Parent.FullName
$runner = Join-Path $frameworkRoot ".zeus\v3\scripts\run.py"

python $runner --project-root $projectRoot @args
'''


def generate_start_sh(framework_root: Path, project_root: Path) -> str:
    import os
    rel = Path(os.path.relpath(framework_root, project_root))
    rel_str = str(rel).replace("\\", "/")
    return rf'''#!/usr/bin/env bash
# Auto-generated by Zeus v3 init
FRAMEWORK_ROOT="${{ZEUS_FRAMEWORK_ROOT:-}}"
if [ -z "$FRAMEWORK_ROOT" ]; then
    if [ -f "$(dirname "$0")/../.framework" ]; then
        FRAMEWORK_ROOT="$(cat "$(dirname "$0")/../.framework")"
    fi
fi
if [ -z "$FRAMEWORK_ROOT" ]; then
    FRAMEWORK_ROOT="$(cd "$(dirname "$0")/{rel_str}" && pwd)"
fi
PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
python "$FRAMEWORK_ROOT/.zeus/v3/scripts/run.py" --project-root "$PROJECT_ROOT" "$@"
'''


def init_project(project_root: Path, framework_root: Path, force: bool = False) -> list[str]:
    created: list[str] = []
    zeus_dir = project_root / ".zeus" / "v3"
    zeus_dir.mkdir(parents=True, exist_ok=True)

    # config.json
    config_path = zeus_dir / "config.json"
    if not config_path.exists() or force:
        write_json(config_path, DEFAULT_CONFIG)
        created.append(str(config_path))

    # task.json.template
    template_path = zeus_dir / "task.json.template"
    if not template_path.exists() or force:
        write_json(template_path, EMPTY_TASK_TEMPLATE)
        created.append(str(template_path))

    # .framework marker
    framework_marker = project_root / ".zeus" / ".framework"
    if not framework_marker.exists() or force:
        framework_marker.write_text(str(framework_root.resolve()), encoding="utf-8")
        created.append(str(framework_marker))

    # start.ps1
    start_ps1 = zeus_dir / "start.ps1"
    if not start_ps1.exists() or force:
        start_ps1.write_text(generate_start_ps1(framework_root, project_root), encoding="utf-8")
        created.append(str(start_ps1))

    # start.sh
    start_sh = zeus_dir / "start.sh"
    if not start_sh.exists() or force:
        start_sh.write_text(generate_start_sh(framework_root, project_root), encoding="utf-8")
        created.append(str(start_sh))

    # Directories
    for sub in ("agent-workspaces", "ai-logs", "specs", "templates"):
        (zeus_dir / sub).mkdir(exist_ok=True)

    return created


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Initialize a Zeus v3 business project")
    parser.add_argument("--project-root", required=True, help="Business project root directory")
    parser.add_argument("--framework-root", default=None, help="Zeus framework repository root")
    parser.add_argument("--force", action="store_true", help="Overwrite existing files")
    args = parser.parse_args(argv)

    project_root = Path(args.project_root).resolve()
    if args.framework_root:
        framework_root = Path(args.framework_root).resolve()
    else:
        framework_root = Path(__file__).resolve().parent.parent.parent.parent.parent

    if not (framework_root / ".zeus" / "v3" / "scripts" / "run.py").exists():
        print(f"[ERROR] Framework root does not look like a Zeus repository: {framework_root}")
        return 1

    created = init_project(project_root, framework_root, force=args.force)
    print(f"[INIT] Project initialized at {project_root}")
    for c in created:
        print(f"  + {c}")
    print(f"\nTo start: cd {project_root} && .zeus/v3/start.ps1 --mode serve")
    return 0


if __name__ == "__main__":
    sys.exit(main())
